### ISSUE TITLE
Equals not found with advanced compilation

### ISSUE THREAD

**Issue by dehli** [henryw374/cljs.java-time#8]
Hi, thanks for all the work you've done with all your libraries! I ran into an issue with tick when targeting JavaScript and I think it's an externs issue with this library. This is the issue I had created on tick's side https://github.com/juxt/tick/issues/124. 

When I run the below code with advanced compilation I'm getting the following error:

```clj
(ns core-test
  (:require [cljs.test :refer [deftest is]]
            [java.time :refer [Instant]]))

(deftest instant-equality
  (is (= (.parse Instant "2020-11-14T05:59:33.757Z")
         (.parse Instant "2020-11-14T05:59:33.757Z"))))
```

```shell
ERROR in (instant-equality) (TypeError:NaN:NaN)
expected: (= (.parse Instant "2020-11-14T05:59:33.757Z") (.parse Instant "2020-11-14T05:59:33.757Z"))
  actual: #object[TypeError TypeError: this.$equals$ is not a function]
```

**Comment by henryw374** [comment]
Hi,

I've had a look at this and there's something about what shadow is doing that I don't understand.. perhaps you know, or if not maybe we can take it to Thomas Heller.

If I do a :node-script , release build - the equals method is found - but - the output is not fully minified - as expected I guess bc this is node, not browser.

but the output for the node-test release build does look fully minified. Is this expected/normal?

I can also do a release browser build, where I expect to see minified output and I do.. but equality works in that case.

So my guess is that either node-test shouldn't be minifying, or if it is, then for some reason it is not picking up externs

**Comment by dehli** [comment]
Thanks! I'll investigate some more and reach out to Thomas if needed. Cheers!

**Comment by thheller** [comment]
shadow-cljs does not include externs specified in `deps.cljs` by default. So [these](https://github.com/henryw374/cljs.java-time/blob/master/src/cljsjs/js-joda/common/js-joda-dup.ext.js) won't be used and they include `equals`. The trouble with generated externs like these is that they usually are far too broad and instead of including only the actually used names they contain "extra". Given how Closure works these extra names will also never be renamed regardless of context, even when they are in a context where they could and should be. This can also negatively impact DCE.

Ideally libraries instead add externs inference `^js` hints whereever actually needed but shadow-cljs users can also just include `:compiler-options {:externs ["cljsjs/js-joda/common/js-joda-dup.ext.js"]}` in their build config.

**Comment by henryw374** [comment]
Ah thanks @thheller I didn't know that. What I still don't understand then is why shadow browser builds with this library seem to work ok under advanced compilation, whereas the node-test build didn't work?

**Comment by thheller** [comment]
For `:browser` builds shadow-cljs actually processes all JS that goes into the build so that includes `js-joda`. While processing it can extract slightly more externs information and be a little bit smarter about them.

Any node-related build does not process JS dependencies at all as node will provide them so it will miss some of the extra info.

**Comment by henryw374** [comment]
ok makes sense now. thanks

**Comment by dehli** [comment]
I'm going to go ahead and close this since it's superseded by https://github.com/henryw374/cljc.java-time/issues/17 Feel free to reopen if you want!

**Comment by henryw374** [comment]
ah - was just typing that :) I've put a note in the readme to inform users about this and created a corresponding issue in cljc.java-time lib (where these ^js hints could go)
